# Generated by Django 3.2.6 on 2021-08-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210803_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='set the true when the user has verified its email address', verbose_name='verified'),
        ),
    ]
